### PR TITLE
Additional edits

### PR DESCRIPTION
**Pull request by cgpotts**
Here's some additional work, especially on the models section.

I think the paper is in really good shape. At a high-level, my only wish is that it played up more the fact that we are releasing this new corpus that was created like a psycholinguistic experiment, and that we are in turn evaluating our model partly by how it compares with humans. This is all sort of implicit in the current version, which is okay, but many of our readers will miss it, so we should find ways to be more direct about this goal and what we did to achieve it.

Perhaps we could enlist @hawkrobe to help with this prose. There are a few to-dos that suggest places where it could be added, especially in section 4. And it would be healthy to make section 2 longer.

### CODE REVIEW

**Comment by hawkrobe** [comment]
This is great! I'd be happy to take another pass over the manuscript this week. In addition to playing up the novelty of the corpus, I can also integrate the wordnet specificity analysis I finished last week.

**Comment by cgpotts** [comment]
Oh, that's excellent, thanks @hawkrobe!

**Comment by futurulus** [comment]
Great!

Do either of you have interesting citations for values of \alpha used in particular applications (Section 5.3)?

@hawkrobe—In addition to the Wordnet analysis, there are a couple of other things you could check out if you have time:

- Use bootstrap confidence intervals in Figure 4
- Check the exact figure for overall human accuracy in the corpus and give it to two decimal places in Table 3
- Mention if there a good perceptual reason for the website to be white-on-black (Figure 1)

**Comment by cgpotts** [comment]
@futurulus For matching human performance, alpha/lambda is very low in Kao-etal:2014 (0.36) but high in Bergen et al, 'That's what she (could have) said: how alternative utterances affect language use'. Is that the kind of thing you mean? Both of these are lexical uncertainty models, though, so I am not sure the comparison is fair. See also page 32 of https://osf.io/vswmz/

**Comment by hawkrobe** [comment]
@futurulus : great, I'll add those to my to-do list. There are a few other minor clean-up jobs I had in mind, like explaining our exclusion criteria and checking the histogram of repeat turkers (e.g. to see that the analyses still come out if we remove the super-turkers). 

With respect to $\alpha$ citations, the OSF preprint Chris linked to is the closest thing to a 'meta-analysis' comparing RSA across a bunch of different datasets. From my own experience, it's varied a lot depending on the setup and I'm not sure we know why yet... For the Q&A work, it was inferred to be around 8 in a bayesian data analysis; for the basic-level work, it was inferred to be around 10... But in some computational experiments, I had to set it closer to 1 to get the right qualitative behavior.

**Comment by cgpotts** [comment]
Thanks, @hawkrobe. `alpha=10` is high! Anyway, feel free to expand the corpus description. I think we benefit from saying more there, to emphasize that this wasn't a haphazard crowdsourcing effort done just to get a bunch of annotations to justify our favorite model.

**Comment by hawkrobe** [comment]
Agreed!

**Pull request merged**
